# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive
- mapcounter
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 目录
toc: 
  enable: true
  number: false

# Gitment comments
gitment:
  enable: true
  owner: 20541494
  repo: qingnansun.github.io
  client_id: 1b8f252cb212a5ede7fc
  client_secret: 7bf7a65f0a99fbd9b14121531cd696301eb9308c